[project]
name = "pmd-demo-tools"
version = "0.0.1"
requires-python = ">=3.11.10"
description = "PMD Demonstrator utilities"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}
packages = ["pmd_demo_tools"]